### PR TITLE
Added requirements file

### LINKED ISSUE #16: Add requirements file
Add python dependencies in **`requirements.txt`** file and update the installing procedure in README.

### PR DESCRIPTION
**Pull request by akshgpt7**
Closes #16

### CODE REVIEW

**Comment by Vibhu-Agarwal** [comment]
@akshgpt7 
> Fixes issue #16.

The PR desc. is not a proper keyword. Read [this](https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords).

**Comment by akshgpt7** [comment]
@Vibhu-Agarwal , I can't understand what else to add to the file, since using ```pip install -r requirements.txt``` is working and installing all modules required.

**Comment by Vibhu-Agarwal** [comment]
Quoting from [this article](https://medium.com/@boscacci/why-and-how-to-make-a-requirements-txt-f329c685181e)

> The problem we run into when we share our Python code is this: Not everyone has the same packages, or the same versions of those packages, installed and ready to rock when they grab your code from GitHub and try to run it.


Sure, by installing the four libraries currently mentioned in the README, executes the code, but some time in future, the dependencies might not always favour us. Maybe sometime in future, one of the libraries gets updated with some errors (yes, sometimes they do - even after thorough reviews from a lot of experienced mentors) and so our app fails to run because one of its dependencies isn't imported correctly or fails on a certain test case. [See [Regression](https://en.wikipedia.org/wiki/Software_regression)] 

So it's always better to include what you have on your system and of what version so that you're sure that other person installs the same version of libraries.

**Comment by akshgpt7** [comment]
So I have to mention the latest version of all packages in the file?

**Comment by Vibhu-Agarwal** [comment]
@akshgpt7 Please READ!
Official docs are the best resource of learning and then there are articles lying all around.
In one of the comments, I mentioned _What is a requirements file and how to add it_ and in my last comment, I quoted from an article and mentioned its link as well.
You'll get enough understanding by going through them once.

**Comment by akshgpt7** [comment]
I've mentioned the version of modules, so that future changes in the module do not affect the app.

**Comment by Vibhu-Agarwal** [comment]
@akshgpt7 You never manually add versions in the requirements file.
You use pip freeze to show versions of modules installed.
Again, PLEASE READ the articles provided in earlier comments to get a better understanding. The links are provided for a reason.

**Pull request closed without merging**
